# Generated by Django 3.0.2 on 2020-01-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20200127_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.CharField(
                choices=[('Extinct', 'Ex'), ('Extinct in the Wild', 'Ew'), ('Critically Endangered', 'Cr'),
                         ('Endangered', 'En'), ('Vulnerable', 'Vu'), ('Near Threatened', 'Nt'), ('Least Concern', 'Lc'),
                         ('Data Deficient', 'Dd')], default='fj', max_length=128),
            preserve_default=False,
        ),
    ]
