# Generated by Django 3.0.2 on 2020-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('Extinct', 'Extinct'), ('Extinct in the Wild', 'Extinct In The Wild'),
                                            ('Critically Endangered', 'Critically Endangered'),
                                            ('Endangered', 'Endangered'), ('Vulnerable', 'Vulnerable'),
                                            ('Near Threatened', 'Near Threatened'), ('Least Concern', 'Least Concern'),
                                            ('Data Deficient', 'Data Deficient')], max_length=128),
        ),
    ]
