# Generated by Django 3.0.2 on 2020-01-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20200128_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='info',
            field=models.CharField(max_length=1000),
        ),
    ]
