# Generated by Django 3.0.2 on 2020-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_auto_20200128_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='level',
            field=models.CharField(choices=[('Extinct', 'Extinct'), ('Extinct in the Wild', 'Extinct In The Wild'),
                                            ('Critically Endangered', 'Critically Endangered'),
                                            ('Endangered', 'Endangered'), ('Vulnerable', 'Vulnerable'),
                                            ('Near Threatened', 'Near Threatened'), ('Least Concern', 'Least Concern'),
                                            ('Data Deficient', 'Data Deficient')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
