# Generated by Django 3.0.2 on 2020-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_animal_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
