# Generated by Django 3.0.2 on 2020-01-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20200129_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
