# Generated by Django 3.0.2 on 2020-01-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_animal_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='animal',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='info',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='info',
            field=models.CharField(max_length=5000),
        ),
    ]
