# Generated by Django 3.0.2 on 2020-01-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200129_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home',
            field=models.CharField(choices=[('Land', 'Land'), ('Air', 'Air'), ('Water', 'Water')], default='Land', max_length=128),
        ),
    ]
