# Generated by Django 3.0.2 on 2020-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_category_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='home',
            field=models.CharField(choices=[('LAND', 'Land'), ('AIR', 'Air'), ('WATER', 'Water')], default='LAND',
                                   max_length=128),
        ),
    ]
